apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-custom-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
      - name: app
        image: kubernetes-user/my-custom-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-custom-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: sample-web
  ports:
    - port: 80
      targetPort: 3000
